language: node_js
sudo: false
branches:
  only:
  - gh-pages
global:
  - URL="https://w3c.github.io/using-aria/ECHIDNA"
  - DECISION="https://lists.w3.org/Archives/Public/public-webapps/2014JulSep/0627.html"
script:
- echo "ok"
after_success:
- curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION"
  --data "token=$TOKEN"